[build]
  publish = "."

[[redirects]]
  from = "/preview"
  to = "/preview.html"
  status = 200

[[redirects]]
  from = "/preview/*"
  to = "/preview.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
